version: "3.8"

services:
  backend:
    image: bulatkonnor228/flexypixel-backend:latest
    container_name: flexypixel-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://localhost:5432/flexydb
      - DATABASE_USER=flexyuser
      - DATABASE_PASSWORD=flexyPixelPassword
    volumes:
      - /var/data/flexypixel/files:/app/files
    networks:
      - flexypixel-net

networks:
  flexypixel-net:
    driver: bridge
