### VPS ###

version: "3.8"

services:
  backend:
    image: bulatkonnor228/flexypixel-backend:latest
    container_name: flexypixel-backend
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://host.docker.internal:5432/flexydb
      - DATABASE_USER=flexyuser
      - DATABASE_PASSWORD=flexyPixelPassword
      - JWT_DOMAIN=flexypixelapi.fun
      - JWT_AUDIENCE=jwt-audience
      - JWT_REALM=flexypixelapp
      - JWT_SECRET=flexypixel2025
      - RESEND_API_KEY
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/data/flexypixel/files:/app/files
      - /var/data/flexypixel/uploads:/app/uploads
      - /var/data/flexypixel/previews:/app/previews
    networks:
      - flexypixel-net

networks:
  flexypixel-net:
    driver: bridge
