ktor:
  application:
    modules:
      - com.flexypixelgalleryapi.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  domain: "flexypixelapi"
  audience: "jwt-audience"
  realm: "flexypixelapp"
  secret: "flexypixel2025"
