name: Deploy to VPS

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run backend tests
        run: ./gradlew test --no-daemon


  build-and-deploy:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: bulatkonnor228/flexypixel-backend:latest

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /opt/flexypixel/FlexyPixelGaleryKtor
            git pull origin main
            docker compose pull backend
            echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" > .env
            docker compose up -d --no-deps --build backend
